### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by tetra-D** [oplS16projects/SkraM---FP-SVG#3]
Scratch the modules for now. I need to figure out where to place exactly what.
About your demo variation - what was the point of renaming definition of canvas I had in my first demo?
I was initially going with naming convention like "m-wnd-type" for main window elements. Probably, similar naming should be used with list window, e.g. "l-wnd-type".

**Comment by ghost** [comment]
Alright we can stick to that naming convention, it made sense. I just renamed them for my own clarity, and it was getting late. Especially the secondary window I tested, I definitely need to rename those. 
Sorry for the confusion.
