### ISSUE TITLE
Milestone 1 running issues

### ISSUE THREAD

**Issue by marksherman** [oplS16projects/SkraM---FP-SVG#6]
- main.rkt has errors when run
- GUI.rkt requires instructions. It runs cleanly, I don't know how to exercise functionality.

**Comment by tetra-D** [comment]
I'm not seeing errors when main.rkt is run. Could you paste in the error message/s you're getting?

**Comment by tetra-D** [comment]
@marksherman I'm not seeing errors when main.rkt is run. Could you paste in the error message/s you're getting? Do the errors show right away?

Capitalized filename GUI.rkt also suggests much older version of a file, which is named gui.rkt now.

**Comment by marksherman** [comment]
I typed the filename incorrectly, it is gui.rkt. 

Anyway, just so you know, here's what happens- that first error appears, then the lower ones trigger in a loop.
<img width="869" alt="screen shot 2016-04-19 at 6 01 42 pm" src="https://cloud.githubusercontent.com/assets/2035149/14657005/e6a1965e-0658-11e6-89af-a3f33ef58f6f.png">

**Comment by tetra-D** [comment]
@marksherman I can't reproduce the error with my setup, but I at least I can see what might be causing it. I've published a new release with a tweak: [milestone 1 patch](https://github.com/oplS16projects/SkraM---FP-SVG/releases/tag/v0.1.1)
Could you run it to see if the same error still appears?

**Comment by marksherman** [comment]
Patch 1 works without error 👍 🎉

**Comment by tetra-D** [comment]
Is updated gui.rkt description sufficient or a complete in depth discussion is expected?
